### PR TITLE
Change Tags.PEER_HOST_IPV4 to a StringTag

### PR DESCRIPTION
**Pull request by wu-sheng**
Related #162

### CODE REVIEW

**Comment by yurishkuro** [comment]
breaking change with little benefit.

**Comment by wu-sheng** [comment]
Set milestone to 1.0

**Comment by tylerbenson** [comment]
With all the other breaking changes going into this next release, I think we should get this in sooner than later.

**Comment by wu-sheng** [comment]
+1 on merging this in RC. @opentracing/otsc

**Comment by yurishkuro** [comment]
We recently made a similar change but in a backwards-compatible way. Why can't we keep the tag as _both_ int and string, and mark the `int` function deprecated?

**Comment by wu-sheng** [comment]
>  Why can't we keep the tag as both int and string, and mark the int function deprecated?

Definitely we can. I think we have broken somethings from 0.30.0 to RC, so maybe we break things together. :P  And provide a more perfect(Remove `@deprecated`s in 0.x) version in 1.0.  Thoughts? @yurishkuro

**Comment by yurishkuro** [comment]
Having broken something with 0.30 is not the best reason to continue breaking people, especially with such a minor improvement that can be easily made backwards compatible. We can leave for the future the decision when `@deprecated` methods can be removed (I'd say in the next major, 2.x)

**Comment by wu-sheng** [comment]
@yurishkuro Sure, I can do some adjustments. But do you have any suggestions about naming? since we will have two ipv4 tag variables.

**Comment by yurishkuro** [comment]
I am suggesting a single constant, but with two methods, `set(BaseSpan<?> span, String tagValue)` and `set(BaseSpan<?> span, int tagValue)`. E.g. you can subclass IntTag <- IntOrStringTag

**Comment by wu-sheng** [comment]
@yurishkuro Sure, I will do this at night.

**Comment by wu-sheng** [comment]
@yurishkuro @tylerbenson I opened a new pull request based on the current master. Closing this. Please check  #184 for more discussion.

**Pull request closed without merging**
