### PR TITLE
Readme document release process for release candidates

### PR DESCRIPTION
**Pull request by pavolloffay**
Do not merge yet!

### CODE REVIEW

**Comment by pavolloffay** [comment]
`publish.sh` contains a bug when the release is performed from the master branch.

**Comment by pavolloffay** [comment]
@carlosalberto could you please review?

**Comment by carlosalberto** [comment]
@pavolloffay Looks great! Now we will be able to release just fine from `master` (when the time comes) :)

**Comment by pavolloffay** [comment]
@carlosalberto  can I merge? Or feel free to merge

**Pull request merged**
