### PR TITLE
V0.31.0 rebased on master (for Final RC).

### PR DESCRIPTION
**Pull request by carlosalberto**
Hey everybody,

In order to prepare to roll out the second (and final) Release Candidate for the 0.31 artifact, I went and rebased the v0.31 branch on top of the misc fixes/patches that master has been received during this development stage.

This will mean that not only a few improvements done on top of the `Scope` concept will be rolled for RC2, but also fixes or adjustments like the usage of `TextMap` as default propagator for `MockTracer`.

Observe that:

1. Rebasing `v0.31` on top of `master` didn't rebase cleanly, but fortunately only minor adjustments were needed.

2. Trying to merge this rebase directly against the `v0.31` branch wouldn't apply cleanly (as it was probably expected). Probably not important, *unless* we want to roll out the final RC from the `v0.31.0` branch directly (in that case I can re-target this PR and do some further, minor adjustment).

Let me know. I went through the changes a pair of times and ran the tests, so hopefully everything is just fine. Hopefully, right after this merge, we can release the RC artifact ;)

### CODE REVIEW

**Comment by carlosalberto** [comment]
Maybe of interest for @yurishkuro @pavolloffay @tylerbenson @tedsuo @malafeev

**Comment by malafeev** [comment]
I don't think it's possible to review 60 files. 
Let's merge it and release RC2.

**Comment by pavolloffay** [comment]
Note that release of `whatever-RC` will not work from the master branch. `publish.sh` will need some adjustments. e.g. `safe_checkout_remote_branch` maybe something more. 

Other option might be to apply `pull rebase master` in `v0.31.0-with-master` branch and create PR to merge it into `v0.31.0` but it's up to you :).

**Comment by yurishkuro** [comment]
> I don't think it's possible to review 60 files. 

Agree, if anything we can review the merge of master

**Comment by carlosalberto** [comment]
@pavolloffay Thanks, hadn't taken that into account. So closing this PR and targeting the 0.31 branch on #233

**Pull request closed without merging**
