### PR TITLE
Add 'isRegistered' check for Global Tracer

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@sjoerdtalsma @pavolloffay Could you review please?

**Comment by sjoerdtalsma** [comment]
In fact I think
```java
if (GlobalTracer.tracer instanceof NoopTracer) {
    GlobalTracer.tracer = tracer;
} else if (!GlobalTracer.tracer.equals(tracer)) { // be lenient for re-registration of same tracer
    throw new IllegalStateException("There is already a current global Tracer registered.");
}
```
would read much nicer as:
```java
if (isRegistered() && !GlobalTracer.tracer.equals(tracer)) {
    throw new IllegalStateException("There is already a current global Tracer registered.");
}
GlobalTracer.tracer = tracer;
```

**Comment by pavolloffay** [comment]
btw. this impl allows to re-register different instances of NoopTracer.

**Comment by bhs** [comment]
@objectiser I don't have any stringent objection to this, but can you explain the use case for my information?

**Comment by yurishkuro** [comment]
> can you explain the use case for my information?

putting the explanation in the method comments would be useful

**Comment by objectiser** [comment]
@bhs added explanation in method comment.

**Comment by bhs** [comment]
@objectiser LGTM, thank you. Not sure if you want to wait for anything before merging, but the rationale makes sense.

**Comment by objectiser** [comment]
@bhs I think it is ok to merge now - and if you could do another release please?

**Pull request merged**
