### PR TITLE
Fixes #145 - Rename package in opentracing-noop to io.opentracing.noop

### LINKED ISSUE #145: Identical packages in opentracing-api and opentracing-noop cause build failure with JDK 9 + jigsaw
Maven dependency on opentracing-util required to use GlobalTracer.get() introduced transitive dependency on opentracing-noop and opentracing-api.
Unfortunately both opentracing-noop and opentracing-api contains the same package "io.opentracing" and this causes error in JDK 9 + jigsaw projects containing module-info.java.

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] module <module_name> reads package io.opentracing from both opentracing.api and opentracing.noop
[ERROR] module  reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.api reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.util reads package io.opentracing from both opentracing.noop and opentracing.api
[ERROR] module opentracing.noop reads package io.opentracing from both opentracing.noop and opentracing.api

It would be good to rename "io.opentracing" package in opentracing-noop to something like "io.opentracing.noop"

### PR DESCRIPTION
**Pull request by kratz74**
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>

### CODE REVIEW

**Comment by kratz74** [comment]
@bhs Just sending requested notification.

**Comment by bhs** [comment]
@kratz74 thank you.

The good news is that this is an improvement. The bad news is that it's a breaking change. Since @pavolloffay offered to think of alternative solutions on #145 I would like to wait for him to offer an opinion before merging. Since we're about to do a 1.0 for OT-Java, my sense is that we should probably merge this since it'll just be more painful to do later.

**Comment by pavolloffay** [comment]
Based on the discussion with @judovana, It seems that this is the best solution to this.

**Comment by bhs** [comment]
@pavolloffay thanks.

I guess we ought to merge, then? Not sure what reasonable alternative we have.

**Comment by bhs** [comment]
(I'll give it 24h)

**Comment by bhs** [comment]
⏰ went off... merged.

Thanks @kratz74!

**Pull request merged**
