### PR TITLE
add missing ThreadLocalActiveSpanSource #173

### PR DESCRIPTION
**Pull request by malafeev**

### CODE REVIEW

**Comment by pavolloffay** [comment]
LGTM, I think we should make it default (it only confuses people why it does not work out of the box)

**Comment by malafeev** [comment]
`ThreadLocalActiveSpanSource` is located in `opentracing-util`.
But `opentracing-util` depends on `opentracing-mock`.
Therefore adding dependency on `opentracing-util` introduces  cyclic reference.

**Comment by pavolloffay** [comment]
I know, I am wondering if we can solve it, e.g. write tests in util without mock tracer

**Comment by malafeev** [comment]
got it!

**Comment by malafeev** [comment]
https://github.com/opentracing/opentracing-java/pull/176

**Comment by malafeev** [comment]
because #176 is merged, this pull request is redundant

**Pull request closed without merging**
