### PR TITLE
Add Examples for async use cases

### PR DESCRIPTION
**Pull request by tylerbenson**
See #183 for further details and discussion.

### CODE REVIEW

**Comment by pavolloffay** [comment]
I would like to see a pointer in the readme with a proper explanation of this example.

**Comment by tylerbenson** [comment]
@pavolloffay  Which read me are you referring to?

**Comment by pavolloffay** [comment]
This one https://github.com/opentracing/opentracing-java/tree/master/opentracing-examples

**Comment by carlosalberto** [comment]
hey Tyler! Sorry for the long iteration time. I think this PR is ready go to. Any objections @pavolloffay @malafeev ?

**Comment by malafeev** [comment]
not from me :)

**Comment by pavolloffay** [comment]
lgtm

**Pull request merged**
