### PR TITLE
Allow an alternate clock implementation to be provided by the tracer …

### PR DESCRIPTION
**Pull request by objectiser**
…implementation

### CODE REVIEW

**Comment by objectiser** [comment]
The change has been implemented to avoid affecting current concrete implementations. However it may be better to explicitly pass the clock via the `AbstractSpanBuilder.createSpan` method to ensure correctly shared between the builder and span?

I've tried out the approach using a clock impl found here: http://stackoverflow.com/a/38658066

Not sure if this should also be included as part of the abstract tracer impl? Or would you prefer to leave it to the concrete impls to provide their own clock impls?

**Comment by michaelsembwever** [comment]
The method of generating nano seconds here is too error prone.
If you really want nano-seconds you're best off going native (to the OS-layer).

Take a look at https://github.com/openzipkin/brave/pull/238 for an example of introducing a clock abstraction.

**Comment by objectiser** [comment]
Ok thanks, will take a look.

Is this PR ok for allowing the clock to be provided?

**Comment by pavolloffay** [comment]
Closing, `-impl` has been removed in https://github.com/opentracing/opentracing-java/pull/121

**Pull request closed without merging**
